services:
  wordpress:
    image: wordpress
    pull_policy: build
    container_name: wordpress_container
    depends_on:
      - mariadb
    restart: always
    build: requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - my-net

  mariadb:
    image: mariadb
    pull_policy: build
    restart: always
    container_name: mariadb_container
    build: requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - my-net
    
  nginx:
    image: nginx
    pull_policy: build
    restart: always
    container_name: nginx_container
    build: requirements/nginx/.
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - my-net
    ports:
      - "443:443"
    depends_on:
      - wordpress

networks:
  my-net:
    name: my-net

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
            device: /home/rchmouk/data/wordpress
            o: bind
            type: none
  database:
    name: database
    driver: local
    driver_opts:
      device: /home/rchmouk/data/mariadb
      o: bind
      type: none

