version: '3.8'

services:
  wordpress:
    image: wp
    depends_on:
      - md
    # restart: always
    build: requirements/wordpress/.
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_USER: new_user
      WORDPRESS_DB_PASSWORD: new_password
      WORDPRESS_DB_HOST: md:3306

  md:
    image: md
    # restart: always
    build: requirements/mariadb/.
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123" 
      MYSQL_DATABASE: redaDb
      MYSQL_USER: new_user
      MYSQL_PASSWORD: new_password
    
  nginx:
    image: ng
    # restart: always
    build: requirements/nginx/.
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress

volumes:
  wp_data:
  db_data:
